CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    address_city TEXT NOT NULL,
    address_state,
)
