DROP TABLE IF EXISTS place;

CREATE TABLE place (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    yelp_id TEXT NOT NULL,
    name TEXT NOT NULL,
    img_url TEXT,
    url TEXT,
    yelp_rating NUMERIC(2),
    location_str TEXT NOT NULL,
    location_city TEXT NOT NULL,
    location_zip TEXT NOT NULL,
    location_st TEXT NOT NULL,
    display_phone TEXT,
    userid INTEGER REFERENCES users(id) ON DELETE SET NULL,
    green_reviews_count INTEGER,
    category TEXT NOT NULL
);





