DROP TABLE IF EXISTS place;

CREATE TABLE place (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    yelpId TEXT NOT NULL,
    name TEXT NOT NULL,
    img_url TEXT,
    url TEXT,
    yelpRating INTEGER,
    location_str TEXT NOT NULL,
    location_city TEXT NOT NULL,
    location_zip TEXT NOT NULL,
    location_st TEXT NOT NULL,
    phone VARCHAR(22),
    userId INTEGER REFERENCES user(id) ON DELETE SET NOT NULL,
    green_reviews_count INTEGER
);





